### ISSUE TITLE
Vertical scrollbar appear and breaks everything

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/dashboard#25]
When on the home page, if there isn't enough space to display the graph, a scrollbar appears and breaks the entire site

![image](https://user-images.githubusercontent.com/47200772/199550346-4c75d451-e2a6-4fa9-9dce-fff21e5b8690.png)

![image](https://user-images.githubusercontent.com/47200772/199550456-e5b07e1b-4ce4-44bc-b129-74650fb5a226.png)

**Comment by Ynng** [comment]
fixed
