### ISSUE TITLE
Truncate instance file directory on windows properly

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/dashboard#31]
On Windows, the path isn't truncated properly

![image](https://user-images.githubusercontent.com/47200772/203146822-64e377b9-8963-4363-ba8c-0a764c733094.png)

Expected:

![image](https://user-images.githubusercontent.com/47200772/203146964-6ae9fd06-3dcc-4010-aede-ddda9322b23c.png)

**Comment by Ynng** [comment]
Should be fixed. can you test? I don't have a windows machine setup

**Comment by CheatCod** [comment]
Fixed
