### ISSUE TITLE
Instance card layout is different on windows

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/dashboard#36]
When client is hosted on Windows:
![image](https://user-images.githubusercontent.com/47200772/204159810-6cc0cc79-45a4-4380-a3ba-258f96721fce.png)

When client is hosted on Ubuntu:
![image](https://user-images.githubusercontent.com/47200772/204159829-c00ac2ef-787a-42b5-b0ce-e1f7f05dd707.png)

**Comment by Ynng** [comment]
This is probably because the names of your instances on your windows client is too short.
This has been fixed
